<?php
function all_modules(): array
{
    return [
        'customer_360' => [
            'id' => 1,
            'code' => 'CUS',
            'title' => 'Customer Information System (Customer 360 + KYC)',
            'description' => 'Customer onboarding, KYC/e-KYC, blacklist/whitelist, and risk profile data',
            'file' => '01_customer_360.php',
            'primary_ref_field' => 'customer_code',
            'primary_name_field' => 'customer_name',
            'amount_field' => 'monthly_income',
            'risk_field' => 'list_status',
            'event_date_field' => 'kyc_date',
            'fields' => [
                ['name' => 'customer_code', 'label' => 'Customer Code', 'type' => 'auto_customer_code', 'required' => true, 'column' => 1],
                ['name' => 'branch_code', 'label' => 'Branch Code', 'type' => 'branch', 'required' => true, 'column' => 1],
                ['name' => 'title_name', 'label' => 'Title', 'type' => 'select', 'required' => true, 'column' => 1, 'options' => ['Mr.', 'Mrs.', 'Ms.', 'Other']],
                ['name' => 'first_name', 'label' => 'First Name', 'type' => 'text', 'required' => true, 'column' => 1],
                ['name' => 'last_name', 'label' => 'Last Name', 'type' => 'text', 'required' => true, 'column' => 1],
                ['name' => 'cid_tax_id', 'label' => 'Citizen ID / Tax ID', 'type' => 'text', 'required' => true, 'column' => 1],
                ['name' => 'phone_number', 'label' => 'Phone Number', 'type' => 'text', 'required' => true, 'column' => 1],
                ['name' => 'email', 'label' => 'Email', 'type' => 'text', 'required' => false, 'column' => 1],
                ['name' => 'id_card_address', 'label' => 'ID Card Address', 'type' => 'textarea', 'required' => false, 'column' => 1],
                ['name' => 'current_address', 'label' => 'Current Address', 'type' => 'textarea', 'required' => false, 'column' => 1],
                ['name' => 'residence_type', 'label' => 'Residence Type', 'type' => 'select', 'required' => false, 'column' => 1, 'options' => ['Own House', 'Relative House', 'Rental']],
                ['name' => 'housing_expense', 'label' => 'Housing Expense (THB/month)', 'type' => 'number', 'required' => false, 'column' => 1],
                ['name' => 'requested_loan_amount', 'label' => 'Requested Loan Amount', 'type' => 'number', 'required' => false, 'column' => 1],
                [
                    'name' => 'borrower_occupations',
                    'label' => 'Borrower Occupations (Multiple entries allowed)',
                    'type' => 'json_list',
                    'required' => false,
                    'column' => 1,
                    'button_label' => 'Add Borrower Occupation',
                    'list_columns' => [
                        ['key' => 'occupation_name', 'label' => 'Occupation', 'input' => 'select', 'required' => true, 'options_source' => 'occupation'],
                        ['key' => 'occupation_detail', 'label' => 'Occupation Detail', 'input' => 'text', 'required' => false],
                        ['key' => 'workplace', 'label' => 'Workplace / Business Location', 'input' => 'text', 'required' => false],
                        ['key' => 'occupation_type', 'label' => 'Occupation Type', 'input' => 'select', 'required' => true, 'options' => ['Government', 'Private', 'Agriculture', 'Freelance', 'Self-Employed', 'Other']],
                        ['key' => 'income_amount', 'label' => 'Income Amount', 'input' => 'number', 'required' => true],
                        ['key' => 'income_period', 'label' => 'Income Frequency', 'input' => 'select', 'required' => true, 'options' => ['Daily', 'Monthly', 'Yearly']],
                    ],
                ],
                ['name' => 'spouse_title_name', 'label' => 'Spouse Title', 'type' => 'select', 'required' => false, 'column' => 1, 'options' => ['Mr.', 'Mrs.', 'Ms.', 'Other']],
                ['name' => 'spouse_first_name', 'label' => 'Spouse First Name', 'type' => 'text', 'required' => false, 'column' => 1],
                ['name' => 'spouse_last_name', 'label' => 'Spouse Last Name', 'type' => 'text', 'required' => false, 'column' => 1],
                ['name' => 'spouse_cid_tax_id', 'label' => 'Spouse Citizen ID / Tax ID', 'type' => 'text', 'required' => false, 'column' => 1],
                ['name' => 'spouse_phone_number', 'label' => 'Spouse Phone Number', 'type' => 'text', 'required' => false, 'column' => 1],
                ['name' => 'spouse_email', 'label' => 'Spouse Email', 'type' => 'text', 'required' => false, 'column' => 1],
                ['name' => 'spouse_id_card_address', 'label' => 'Spouse ID Card Address', 'type' => 'textarea', 'required' => false, 'column' => 1],
                [
                    'name' => 'spouse_occupations',
                    'label' => 'Spouse Occupations (Multiple entries allowed)',
                    'type' => 'json_list',
                    'required' => false,
                    'column' => 1,
                    'button_label' => 'Add Spouse Occupation',
                    'list_columns' => [
                        ['key' => 'occupation_name', 'label' => 'Occupation', 'input' => 'select', 'required' => true, 'options_source' => 'occupation'],
                        ['key' => 'occupation_detail', 'label' => 'Occupation Detail', 'input' => 'text', 'required' => false],
                        ['key' => 'workplace', 'label' => 'Workplace / Business Location', 'input' => 'text', 'required' => false],
                        ['key' => 'occupation_type', 'label' => 'Occupation Type', 'input' => 'select', 'required' => true, 'options' => ['Government', 'Private', 'Agriculture', 'Freelance', 'Self-Employed', 'Other']],
                        ['key' => 'income_amount', 'label' => 'Income Amount', 'input' => 'number', 'required' => true],
                        ['key' => 'income_period', 'label' => 'Income Frequency', 'input' => 'select', 'required' => true, 'options' => ['Daily', 'Monthly', 'Yearly']],
                    ],
                ],
                [
                    'name' => 'guarantors',
                    'label' => 'Guarantors (Multiple entries allowed)',
                    'type' => 'json_list',
                    'required' => false,
                    'button_label' => 'Add Guarantor',
                    'list_columns' => [
                        ['key' => 'first_name', 'label' => 'First Name', 'input' => 'text', 'required' => false],
                        ['key' => 'last_name', 'label' => 'Last Name', 'input' => 'text', 'required' => false],
                        ['key' => 'phone_number', 'label' => 'Contact Number', 'input' => 'text', 'required' => false],
                        ['key' => 'gender', 'label' => 'Gender', 'input' => 'select', 'required' => false, 'options' => ['Male', 'Female', 'Other']],
                        ['key' => 'birth_date', 'label' => 'Birth Date', 'input' => 'date', 'required' => false],
                        ['key' => 'occupation', 'label' => 'Occupation', 'input' => 'select', 'required' => false, 'options_source' => 'occupation'],
                        ['key' => 'id_card_address', 'label' => 'ID Card Address', 'input' => 'text', 'required' => false],
                    ],
                ],
                [
                    'name' => 'children',
                    'label' => 'Children (Multiple entries allowed)',
                    'type' => 'json_list',
                    'required' => false,
                    'button_label' => 'Add Child',
                    'list_columns' => [
                        ['key' => 'first_name', 'label' => 'First Name', 'input' => 'text', 'required' => true],
                        ['key' => 'last_name', 'label' => 'Last Name', 'input' => 'text', 'required' => false],
                        ['key' => 'phone_number', 'label' => 'Contact Number', 'input' => 'text', 'required' => true],
                        ['key' => 'gender', 'label' => 'Gender', 'input' => 'select', 'required' => true, 'options' => ['Male', 'Female', 'Other']],
                        ['key' => 'birth_date', 'label' => 'Birth Date', 'input' => 'date', 'required' => true],
                    ],
                ],
                [
                    'name' => 'houses',
                    'label' => 'Houses / Buildings (Multiple entries allowed)',
                    'type' => 'json_list',
                    'required' => false,
                    'button_label' => 'Add House / Building',
                    'list_columns' => [
                        ['key' => 'district', 'label' => 'District', 'input' => 'text', 'required' => true],
                        ['key' => 'province', 'label' => 'Province', 'input' => 'text', 'required' => true],
                        ['key' => 'deed_no', 'label' => 'Deed No.', 'input' => 'text', 'required' => true],
                        ['key' => 'appraisal', 'label' => 'Appraisal Value', 'input' => 'number', 'required' => true],
                    ],
                ],
                [
                    'name' => 'lands',
                    'label' => 'Lands (Multiple entries allowed)',
                    'type' => 'json_list',
                    'required' => false,
                    'button_label' => 'Add Land',
                    'list_columns' => [
                        ['key' => 'district', 'label' => 'District', 'input' => 'text', 'required' => true],
                        ['key' => 'province', 'label' => 'Province', 'input' => 'text', 'required' => true],
                        ['key' => 'deed_no', 'label' => 'Deed No.', 'input' => 'text', 'required' => true],
                        ['key' => 'appraisal', 'label' => 'Appraisal Value', 'input' => 'number', 'required' => true],
                    ],
                ],
                [
                    'name' => 'cars',
                    'label' => 'Cars (Multiple entries allowed)',
                    'type' => 'json_list',
                    'required' => false,
                    'button_label' => 'Add Car',
                    'list_columns' => [
                        ['key' => 'plate_province', 'label' => 'Registration Province', 'input' => 'text', 'required' => true],
                        ['key' => 'plate_no', 'label' => 'License Plate', 'input' => 'text', 'required' => true],
                        ['key' => 'brand_name', 'label' => 'Brand', 'input' => 'select', 'required' => true, 'options_source' => 'car_brand'],
                        ['key' => 'model_name', 'label' => 'Model', 'input' => 'select', 'required' => true, 'depends_on' => 'brand_name', 'options_source' => 'car_model_by_brand'],
                        ['key' => 'model_year', 'label' => 'Model Year', 'input' => 'select', 'required' => true, 'options_source' => 'car_year'],
                    ],
                ],
                [
                    'name' => 'bank_accounts',
                    'label' => 'Bank Accounts (Multiple entries allowed)',
                    'type' => 'json_list',
                    'required' => false,
                    'button_label' => 'Add Bank Account',
                    'list_columns' => [
                        ['key' => 'bank_name', 'label' => 'Bank Name', 'input' => 'text', 'required' => true],
                        ['key' => 'account_no', 'label' => 'Account Number', 'input' => 'text', 'required' => true],
                    ],
                ],
                [
                    'name' => 'id_card_files',
                    'label' => 'ID Card Documents (Up to 1 file)',
                    'type' => 'json_list',
                    'required' => false,
                    'max_items' => 1,
                    'button_label' => 'Add ID Card File',
                    'list_columns' => [
                        ['key' => 'file', 'label' => 'ID Card File', 'input' => 'file', 'required' => true, 'accept' => '.pdf,.jpg,.jpeg,.png,.webp'],
                    ],
                ],
                [
                    'name' => 'house_registration_files',
                    'label' => 'House Registration Documents (Up to 1 file)',
                    'type' => 'json_list',
                    'required' => false,
                    'max_items' => 1,
                    'button_label' => 'Add House Registration File',
                    'list_columns' => [
                        ['key' => 'file', 'label' => 'House Registration File', 'input' => 'file', 'required' => true, 'accept' => '.pdf,.jpg,.jpeg,.png,.webp'],
                    ],
                ],
                [
                    'name' => 'marriage_registration_files',
                    'label' => 'Marriage Registration Documents (Up to 1 file)',
                    'type' => 'json_list',
                    'required' => false,
                    'max_items' => 1,
                    'button_label' => 'Add Marriage Registration File',
                    'list_columns' => [
                        ['key' => 'file', 'label' => 'Marriage Registration File', 'input' => 'file', 'required' => true, 'accept' => '.pdf,.jpg,.jpeg,.png,.webp'],
                    ],
                ],
                [
                    'name' => 'bank_statement_files',
                    'label' => 'Bank Statement Documents (Unlimited uploads)',
                    'type' => 'json_list',
                    'required' => false,
                    'button_label' => 'Add Bank Statement File',
                    'list_columns' => [
                        ['key' => 'file', 'label' => 'Bank Statement File', 'input' => 'file', 'required' => true, 'accept' => '.pdf,.jpg,.jpeg,.png,.webp'],
                    ],
                ],
                [
                    'name' => 'collateral_assets',
                    'label' => 'Collateral Assets (Multiple entries allowed)',
                    'type' => 'json_list',
                    'required' => false,
                    'button_label' => 'Add Collateral Asset',
                    'list_columns' => [
                        ['key' => 'collateral_type', 'label' => 'Collateral Type', 'input' => 'select', 'required' => true, 'options' => ['House', 'Land', 'Car', 'Motorcycle']],
                        ['key' => 'district', 'label' => 'District', 'input' => 'text', 'required' => true],
                        ['key' => 'province', 'label' => 'Province', 'input' => 'text', 'required' => true],
                        ['key' => 'asset_ref_no', 'label' => 'Deed / Registration No.', 'input' => 'text', 'required' => true],
                        ['key' => 'appraisal_value', 'label' => 'Appraisal Value', 'input' => 'number', 'required' => true],
                        ['key' => 'attachment_file', 'label' => 'Collateral Document (PDF)', 'input' => 'file', 'required' => false, 'accept' => '.pdf'],
                        ['key' => 'note', 'label' => 'Note', 'input' => 'text', 'required' => false],
                    ],
                ],
                [
                    'name' => 'liabilities',
                    'label' => 'Liabilities (Multiple entries allowed)',
                    'type' => 'json_list',
                    'required' => false,
                    'button_label' => 'Add Liability',
                    'list_columns' => [
                        ['key' => 'debt_type', 'label' => 'Debt Type', 'input' => 'select', 'required' => true, 'options' => ['Bank', 'Finance/Leasing', 'Credit Card', 'Personal Loan', 'Other Creditor']],
                        ['key' => 'creditor_name', 'label' => 'Financial Institution / Creditor', 'input' => 'text', 'required' => true],
                        ['key' => 'account_or_contract_no', 'label' => 'Account / Contract No.', 'input' => 'text', 'required' => true],
                        ['key' => 'contract_term_months', 'label' => 'Contract Term (Months)', 'input' => 'number', 'required' => false],
                        ['key' => 'outstanding_balance', 'label' => 'Outstanding Balance', 'input' => 'number', 'required' => false],
                    ],
                ],
                ['name' => 'kyc_date', 'label' => 'KYC Check Date', 'type' => 'date', 'required' => false],
            ],
        ],
        'credit_scoring' => [
            'id' => 2,
            'code' => 'SCR',
            'title' => 'ระบบประเมินเครดิตลูกค้าใหม่ (New Customer Credit Assessment)',
            'description' => 'ประเมินลูกค้ายังไม่อนุมัติจากอาชีพ ทรัพย์สิน ภาระครอบครัว และทัศนคติชำระหนี้',
            'file' => '02_credit_scoring.php',
            'primary_ref_field' => 'application_no',
            'primary_name_field' => 'customer_ref',
            'amount_field' => 'score_total',
            'risk_field' => 'pd_band',
            'event_date_field' => 'decision_date',
            'fields' => [
                ['name' => 'application_no', 'label' => 'เลขที่คำขอสินเชื่อ', 'type' => 'text', 'required' => true],
                ['name' => 'customer_ref', 'label' => 'อ้างอิงลูกค้า', 'type' => 'text', 'required' => true],
                ['name' => 'score_total', 'label' => 'คะแนนรวม', 'type' => 'number', 'required' => true],
                ['name' => 'score_components', 'label' => 'องค์ประกอบคะแนน', 'type' => 'textarea', 'required' => false],
                ['name' => 'bureau_summary', 'label' => 'สรุปเครดิตบูโร', 'type' => 'textarea', 'required' => false],
                ['name' => 'model_version', 'label' => 'เวอร์ชันโมเดล', 'type' => 'text', 'required' => true],
                ['name' => 'cutoff_value', 'label' => 'ค่าตัดสินขั้นต่ำ', 'type' => 'number', 'required' => false],
                ['name' => 'pd_band', 'label' => 'ระดับ PD', 'type' => 'select', 'required' => true, 'options' => ['LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH']],
                ['name' => 'decision', 'label' => 'ผลการพิจารณา', 'type' => 'select', 'required' => true, 'options' => ['APPROVE', 'REVIEW', 'REJECT']],
                ['name' => 'override_reason', 'label' => 'เหตุผลการ Override', 'type' => 'textarea', 'required' => false],
                ['name' => 'decision_date', 'label' => 'วันที่ตัดสินใจ', 'type' => 'date', 'required' => false],
            ],
        ],
        'hire_purchase' => [
            'id' => 3,
            'code' => 'HPC',
            'title' => 'Hire Purchase',
            'description' => 'Create contracts from approved customers and calculate installments from credit assessment and policy results.',
            'file' => '03_hire_purchase.php',
            'primary_ref_field' => 'contract_no',
            'primary_name_field' => 'customer_code',
            'amount_field' => 'approved_loan_amount',
            'risk_field' => 'contract_status',
            'event_date_field' => 'first_due_date',
            'fields' => [
                ['name' => 'contract_no', 'label' => 'เลขที่สัญญา', 'type' => 'text', 'required' => true],
                ['name' => 'customer_code', 'label' => 'รหัสลูกค้า', 'type' => 'text', 'required' => true],
                ['name' => 'customer_name', 'label' => 'ชื่อลูกค้า', 'type' => 'text', 'required' => false],
                ['name' => 'policy_code', 'label' => 'รหัสนโยบาย', 'type' => 'text', 'required' => false],
                ['name' => 'policy_name', 'label' => 'ชื่อนโยบาย', 'type' => 'text', 'required' => false],
                ['name' => 'application_no', 'label' => 'อ้างอิงคำขอ', 'type' => 'text', 'required' => false],
                ['name' => 'approved_loan_amount', 'label' => 'วงเงินอนุมัติ', 'type' => 'number', 'required' => true],
                ['name' => 'annual_rate_pct', 'label' => 'ดอกเบี้ยต่อปี (%)', 'type' => 'number', 'required' => true],
                ['name' => 'term_months', 'label' => 'จำนวนงวด (เดือน)', 'type' => 'number', 'required' => true],
                ['name' => 'installment_amount', 'label' => 'ค่างวดต่อเดือน', 'type' => 'number', 'required' => true],
                ['name' => 'first_due_date', 'label' => 'วันครบงวดแรก', 'type' => 'date', 'required' => true],
                ['name' => 'contract_status', 'label' => 'สถานะสัญญา', 'type' => 'select', 'required' => true, 'options' => ['ACTIVE', 'CLOSED', 'NPL']],
                ['name' => 'contract_note', 'label' => 'หมายเหตุ', 'type' => 'textarea', 'required' => false],
            ],
        ],
        'installments' => [
            'id' => 4,
            'code' => 'INS',
            'title' => 'Installments Management',
            'description' => 'Review installments, receive periodic payments, and keep payment history by contract.',
            'file' => '04_installments.php',
            'primary_ref_field' => 'payment_no',
            'primary_name_field' => 'contract_no',
            'amount_field' => 'paid_amount',
            'risk_field' => 'payment_status',
            'event_date_field' => 'payment_date',
            'fields' => [
                ['name' => 'payment_no', 'label' => 'รหัสรายการรับชำระ', 'type' => 'text', 'required' => true],
                ['name' => 'contract_no', 'label' => 'เลขที่สัญญา', 'type' => 'text', 'required' => true],
                ['name' => 'customer_code', 'label' => 'รหัสลูกค้า', 'type' => 'text', 'required' => false],
                ['name' => 'installment_no', 'label' => 'งวดที่', 'type' => 'number', 'required' => true],
                ['name' => 'due_date', 'label' => 'วันครบงวด', 'type' => 'date', 'required' => false],
                ['name' => 'payment_date', 'label' => 'วันที่รับชำระ', 'type' => 'date', 'required' => true],
                ['name' => 'installment_due', 'label' => 'ยอดงวด', 'type' => 'number', 'required' => false],
                ['name' => 'late_penalty', 'label' => 'ดอกเบี้ยผิดนัด', 'type' => 'number', 'required' => false],
                ['name' => 'collection_fee', 'label' => 'ค่าติดตามทวงถาม', 'type' => 'number', 'required' => false],
                ['name' => 'paid_amount', 'label' => 'ยอดรับชำระ', 'type' => 'number', 'required' => true],
                ['name' => 'payment_channel', 'label' => 'ช่องทางชำระ', 'type' => 'select', 'required' => true, 'options' => ['CASH', 'BANK_TRANSFER', 'QR', 'AUTO_DEBIT', 'OTHER']],
                ['name' => 'receipt_no', 'label' => 'เลขที่ใบเสร็จ', 'type' => 'text', 'required' => false],
                ['name' => 'payment_status', 'label' => 'สถานะรับชำระ', 'type' => 'select', 'required' => true, 'options' => ['PAID', 'PARTIAL', 'REVERSED']],
                ['name' => 'payment_note', 'label' => 'หมายเหตุ', 'type' => 'textarea', 'required' => false],
            ],
        ],
        'affordability_dti' => [
            'id' => 6,
            'code' => 'DTI',
            'title' => 'Affordability / DTI Assessment',
            'description' => 'Calculate DTI/DSR and maximum affordable installment capacity.',
            'file' => '03_affordability_dti.php',
            'primary_ref_field' => 'case_no',
            'primary_name_field' => 'customer_ref',
            'amount_field' => 'max_installment',
            'risk_field' => 'dti_result',
            'event_date_field' => 'assessment_date',
            'fields' => [
                ['name' => 'case_no', 'label' => 'เลขที่เคส', 'type' => 'text', 'required' => true],
                ['name' => 'customer_ref', 'label' => 'อ้างอิงลูกค้า', 'type' => 'text', 'required' => true],
                ['name' => 'income_streams', 'label' => 'แหล่งรายได้', 'type' => 'textarea', 'required' => false],
                ['name' => 'monthly_income', 'label' => 'รายได้รวมต่อเดือน', 'type' => 'number', 'required' => true],
                ['name' => 'expense_baseline', 'label' => 'ค่าใช้จ่ายพื้นฐาน', 'type' => 'number', 'required' => true],
                ['name' => 'existing_debts', 'label' => 'หนี้เดิมต่อเดือน', 'type' => 'number', 'required' => true],
                ['name' => 'dependents', 'label' => 'จำนวนผู้อุปการะ', 'type' => 'number', 'required' => false],
                ['name' => 'volatility_factor', 'label' => 'ปัจจัยความผันผวน', 'type' => 'number', 'required' => false],
                ['name' => 'stress_buffer_pct', 'label' => 'ส่วนกันชนความเสี่ยง (%)', 'type' => 'number', 'required' => false],
                ['name' => 'dti_result', 'label' => 'ผล DTI/DSR', 'type' => 'text', 'required' => false],
                ['name' => 'max_installment', 'label' => 'ค่างวดสูงสุด', 'type' => 'number', 'required' => false],
                ['name' => 'assessment_date', 'label' => 'วันที่ประเมิน', 'type' => 'date', 'required' => false],
            ],
        ],
        'collections_workflow' => [
            'id' => 5,
            'code' => 'COL',
            'title' => 'ระบบติดตามทวงถามหนี้ (Collections Workflow)',
            'description' => 'จัดการงานทวงหนี้ตาม bucket, PTP, disposition และ escalation',
            'file' => '04_collections_workflow.php',
            'primary_ref_field' => 'collection_case_no',
            'primary_name_field' => 'contract_no',
            'amount_field' => 'ptp_amount',
            'risk_field' => 'bucket_name',
            'event_date_field' => 'ptp_date',
            'fields' => [
                ['name' => 'collection_case_no', 'label' => 'เลขที่เคสทวงถาม', 'type' => 'text', 'required' => true],
                ['name' => 'contract_no', 'label' => 'เลขที่สัญญา', 'type' => 'text', 'required' => true],
                ['name' => 'dpd_days', 'label' => 'จำนวนวันค้างชำระ', 'type' => 'number', 'required' => true],
                ['name' => 'bucket_name', 'label' => 'Bucket ค้างชำระ', 'type' => 'select', 'required' => true, 'options' => ['1-7', '8-30', '31-60', '61-90', '90+']],
                ['name' => 'contact_channel', 'label' => 'ช่องทางติดต่อ', 'type' => 'select', 'required' => true, 'options' => ['CALL', 'SMS', 'LINE', 'VISIT']],
                ['name' => 'contact_outcome', 'label' => 'ผลการติดต่อ', 'type' => 'textarea', 'required' => false],
                ['name' => 'ptp_date', 'label' => 'วันที่ PTP', 'type' => 'date', 'required' => false],
                ['name' => 'ptp_amount', 'label' => 'ยอด PTP', 'type' => 'number', 'required' => false],
                ['name' => 'collector_name', 'label' => 'ผู้ติดตามหนี้', 'type' => 'text', 'required' => false],
                ['name' => 'recording_reference', 'label' => 'อ้างอิงไฟล์บันทึกเสียง', 'type' => 'text', 'required' => false],
                ['name' => 'escalation_level', 'label' => 'ระดับการยกระดับ', 'type' => 'text', 'required' => false],
            ],
        ],
        'portfolio_branch' => [
            'id' => 7,
            'code' => 'PBR',
            'title' => 'ระบบบริหารพอร์ตต่อสาขา (Portfolio / Branch Performance)',
            'description' => 'วิเคราะห์ KPI สาขาและเจ้าหน้าที่, cohort, vintage และ risk heatmap',
            'file' => '05_portfolio_branch.php',
            'primary_ref_field' => 'branch_code',
            'primary_name_field' => 'branch_name',
            'amount_field' => 'portfolio_yield',
            'risk_field' => 'risk_heatmap_zone',
            'event_date_field' => 'reporting_date',
            'fields' => [
                ['name' => 'branch_code', 'label' => 'รหัสสาขา', 'type' => 'branch', 'required' => true],
                ['name' => 'branch_name', 'label' => 'ชื่อสาขา', 'type' => 'text', 'required' => true],
                ['name' => 'officer_name', 'label' => 'ชื่อเจ้าหน้าที่', 'type' => 'text', 'required' => false],
                ['name' => 'origination_cohort', 'label' => 'กลุ่มรุ่นปล่อยสินเชื่อ', 'type' => 'text', 'required' => false],
                ['name' => 'approval_rate', 'label' => 'อัตราอนุมัติ (%)', 'type' => 'number', 'required' => false],
                ['name' => 'roll_rate', 'label' => 'อัตราไหลต่อช่วง (%)', 'type' => 'number', 'required' => false],
                ['name' => 'npl_rate', 'label' => 'อัตรา NPL (%)', 'type' => 'number', 'required' => false],
                ['name' => 'portfolio_yield', 'label' => 'ผลตอบแทนพอร์ต (%)', 'type' => 'number', 'required' => false],
                ['name' => 'delinquency_curve', 'label' => 'เส้นโค้งการค้างชำระ', 'type' => 'textarea', 'required' => false],
                ['name' => 'risk_heatmap_zone', 'label' => 'โซนความเสี่ยง', 'type' => 'text', 'required' => false],
                ['name' => 'reporting_date', 'label' => 'วันที่รายงาน', 'type' => 'date', 'required' => false],
            ],
        ],
        'delinquency_dpd' => [
            'id' => 8,
            'code' => 'DPD',
            'title' => 'ระบบติดตามการค้างชำระ (Delinquency & DPD Engine)',
            'description' => 'คำนวณ DPD แบบ real-time และออกรายงาน aging',
            'file' => '06_delinquency_dpd.php',
            'primary_ref_field' => 'contract_no',
            'primary_name_field' => 'customer_ref',
            'amount_field' => 'installment_due',
            'risk_field' => 'dpd_bucket',
            'event_date_field' => 'snapshot_date',
            'fields' => [
                ['name' => 'contract_no', 'label' => 'เลขที่สัญญา', 'type' => 'text', 'required' => true],
                ['name' => 'customer_ref', 'label' => 'อ้างอิงลูกค้า', 'type' => 'text', 'required' => true],
                ['name' => 'due_date', 'label' => 'วันครบกำหนดชำระ', 'type' => 'date', 'required' => true],
                ['name' => 'last_paid_date', 'label' => 'วันที่ชำระล่าสุด', 'type' => 'date', 'required' => false],
                ['name' => 'installment_due', 'label' => 'ยอดค่างวด', 'type' => 'number', 'required' => false],
                ['name' => 'grace_days', 'label' => 'จำนวนวันผ่อนผัน', 'type' => 'number', 'required' => false],
                ['name' => 'holiday_rule', 'label' => 'กติกาวันหยุด', 'type' => 'text', 'required' => false],
                ['name' => 'dpd_days', 'label' => 'จำนวนวัน DPD', 'type' => 'number', 'required' => true],
                ['name' => 'dpd_bucket', 'label' => 'Bucket ค้างชำระ', 'type' => 'select', 'required' => true, 'options' => ['1-7', '8-30', '31-60', '61-90', '90+']],
                ['name' => 'roll_status', 'label' => 'สถานะ Roll / Cure', 'type' => 'text', 'required' => false],
                ['name' => 'snapshot_date', 'label' => 'วันที่บันทึกภาพข้อมูล', 'type' => 'date', 'required' => false],
            ],
        ],
        'npl_recovery' => [
            'id' => 9,
            'code' => 'NPL',
            'title' => 'ระบบบริหารหนี้เสีย (NPL / Recovery / Debt Sale)',
            'description' => 'จัดการ restructure, settlement, write-off, debt sale และสถานะทางกฎหมาย',
            'file' => '07_npl_recovery.php',
            'primary_ref_field' => 'npl_case_no',
            'primary_name_field' => 'contract_no',
            'amount_field' => 'recovery_cashflow',
            'risk_field' => 'legal_stage',
            'event_date_field' => 'next_action_date',
            'fields' => [
                ['name' => 'npl_case_no', 'label' => 'เลขที่เคส NPL', 'type' => 'text', 'required' => true],
                ['name' => 'contract_no', 'label' => 'เลขที่สัญญา', 'type' => 'text', 'required' => true],
                ['name' => 'npl_status', 'label' => 'สถานะ NPL', 'type' => 'text', 'required' => true],
                ['name' => 'collateral_status', 'label' => 'สถานะหลักประกัน', 'type' => 'text', 'required' => false],
                ['name' => 'recovery_strategy', 'label' => 'กลยุทธ์ Recovery', 'type' => 'select', 'required' => true, 'options' => ['RESTRUCTURE', 'SETTLEMENT', 'WRITE_OFF', 'REPOSSESS', 'LITIGATION', 'DEBT_SALE']],
                ['name' => 'recovery_cashflow', 'label' => 'กระแสเงินสดรับคืน', 'type' => 'number', 'required' => false],
                ['name' => 'sale_pool_code', 'label' => 'รหัส Sale Pool', 'type' => 'text', 'required' => false],
                ['name' => 'buyer_name', 'label' => 'ชื่อผู้ซื้อหนี้', 'type' => 'text', 'required' => false],
                ['name' => 'legal_stage', 'label' => 'ขั้นตอนกฎหมาย', 'type' => 'text', 'required' => false],
                ['name' => 'next_action_date', 'label' => 'วันที่ดำเนินการถัดไป', 'type' => 'date', 'required' => false],
            ],
        ],
        'credit_policy' => [
            'id' => 10,
            'code' => 'POL',
            'title' => 'ระบบกำหนดนโยบายสินเชื่อ (Credit Policy Engine)',
            'description' => 'กำหนดนโยบายจากอาชีพ รายได้ และหลักทรัพย์ค้ำประกัน พร้อมโครง 9 หัวข้อแบบเลือกจาก dropdown',
            'file' => '08_credit_policy.php',
            'branch_independent' => true,
            'hide_common_context_fields' => true,
            'search_placeholder' => 'ค้นหารหัสนโยบาย, ชื่อนโยบาย, กลยุทธ์เครดิต',
            'primary_ref_field' => 'policy_code',
            'primary_name_field' => 'policy_name',
            'amount_field' => 'recommended_loan_amount',
            'risk_field' => 'customer_segmentation',
            'event_date_field' => 'effective_date',
            'fields' => [
                ['name' => 'policy_code', 'label' => 'รหัสนโยบาย', 'type' => 'text', 'required' => true, 'column' => 1],
                ['name' => 'policy_name', 'label' => 'ชื่อนโยบาย', 'type' => 'text', 'required' => true, 'column' => 1],
                ['name' => 'policy_version', 'label' => 'เวอร์ชัน', 'type' => 'text', 'required' => true, 'column' => 1],
                ['name' => 'effective_date', 'label' => 'วันที่เริ่มใช้', 'type' => 'date', 'required' => true, 'column' => 1],
                ['name' => 'customer_job_ref', 'label' => 'อาชีพลูกค้าอ้างอิง', 'type' => 'occupation', 'required' => true, 'column' => 1],
                ['name' => 'income_band_ref', 'label' => 'ช่วงรายได้ลูกค้า (บาท/เดือน)', 'type' => 'select', 'required' => true, 'column' => 1, 'options' => ['GT_10000', 'GT_20000', 'GT_30000', 'GT_40000', 'GT_50000', 'GT_60000', 'GT_70000', 'GT_80000', 'GT_90000', 'GT_100000']],
                ['name' => 'collateral_type_ref', 'label' => 'หลักทรัพย์ค้ำประกันอ้างอิง', 'type' => 'select', 'required' => true, 'column' => 1, 'options' => ['HOUSE', 'LAND', 'CAR', 'MOTORCYCLE', 'MIXED', 'NONE']],
                ['name' => 'credit_strategy', 'label' => '1) กลยุทธ์สินเชื่อ (Credit Strategy)', 'type' => 'select', 'required' => true, 'column' => 2, 'options' => ['CONSERVATIVE', 'BALANCED_GROWTH', 'SUBPRIME_CONTROLLED', 'AGGRESSIVE_EXPANSION', 'RECOVERY_FOCUS']],
                ['name' => 'customer_segmentation', 'label' => '2) การแบ่งกลุ่มลูกค้า (Customer Segmentation)', 'type' => 'select', 'required' => true, 'column' => 2, 'options' => ['LOW_RISK_STABLE', 'MASS_MARKET_BALANCED', 'NEW_TO_CREDIT', 'SEASONAL_INCOME', 'HIGH_RISK_MONITORED']],
                ['name' => 'eligibility_underwriting', 'label' => '3) เกณฑ์อนุมัติขั้นต่ำ (Eligibility & Underwriting)', 'type' => 'select', 'required' => true, 'column' => 2, 'options' => ['STRICT_SCORE_AND_DSR', 'COLLATERAL_LED_APPROVAL', 'CASHFLOW_FIRST', 'BUREAU_REQUIRED', 'MANUAL_COMMITTEE']],
                ['name' => 'credit_structure', 'label' => '4) โครงสร้างสินเชื่อ (Credit Structure)', 'type' => 'select', 'required' => true, 'column' => 2, 'options' => ['LOW_INSTALLMENT_LONG_TERM', 'BALANCED_STRUCTURE', 'HIGH_DOWNPAYMENT', 'COLLATERAL_MAXIMIZE', 'STEP_UP_INSTALLMENT']],
                ['name' => 'risk_scoring_pd', 'label' => '5) คะแนนความเสี่ยง / PD (Risk Scoring / PD)', 'type' => 'select', 'required' => true, 'column' => 2, 'options' => ['PD_CEILING_3', 'PD_CEILING_5', 'PD_CEILING_8', 'PD_CEILING_12', 'MANUAL_OVERRIDE_TRACKED']],
                ['name' => 'pricing_policy', 'label' => '6) นโยบายราคา (Pricing Policy)', 'type' => 'select', 'required' => true, 'column' => 2, 'options' => ['RISK_BASED_LOW_SPREAD', 'RISK_BASED_STANDARD', 'RISK_BASED_HIGH_SPREAD', 'PROMO_FIXED_RATE', 'FEE_HEAVY_LOW_RATE']],
                ['name' => 'monitoring_ews', 'label' => '7) ติดตามและเตือนล่วงหน้า (Monitoring & EWS)', 'type' => 'select', 'required' => true, 'column' => 3, 'options' => ['MONTHLY_LIGHT', 'MONTHLY_STANDARD', 'WEEKLY_HIGH_RISK', 'REALTIME_ALERTS', 'FIELD_VISIT_TRIGGER']],
                ['name' => 'collections_npl', 'label' => '8) ทวงหนี้และ NPL (Collections & NPL)', 'type' => 'select', 'required' => true, 'column' => 3, 'options' => ['SOFT_FIRST', 'SOFT_TO_HARD_30D', 'RESTRUCTURE_PRIORITY', 'LEGAL_FAST_TRACK', 'WRITE_OFF_STRICT']],
                ['name' => 'governance_exception', 'label' => '9) อำนาจอนุมัติและข้อยกเว้น (Governance & Exception)', 'type' => 'select', 'required' => true, 'column' => 3, 'options' => ['NO_OVERRIDE', 'LIMITED_OVERRIDE', 'COMMITTEE_ONLY', 'CENTRAL_APPROVAL', 'FULL_AUDIT_TRAIL']],
                ['name' => 'max_dsr_pct', 'label' => 'DSR สูงสุด (%) (เพดานภาระหนี้ต่อรายได้)', 'type' => 'number', 'required' => false, 'column' => 3],
                ['name' => 'max_ltv_pct', 'label' => 'LTV สูงสุด (%) (เพดานวงเงินกู้ต่อมูลค่าหลักทรัพย์)', 'type' => 'number', 'required' => false, 'column' => 3],
                ['name' => 'max_tenor_month', 'label' => 'Tenor สูงสุด (เดือน)', 'type' => 'number', 'required' => false, 'column' => 3],
                ['name' => 'policy_interest_rate_pct', 'label' => 'อัตราดอกเบี้ยอ้างอิงต่อปี (%)', 'type' => 'number', 'required' => false, 'column' => 3],
                ['name' => 'debt_obligation_ref', 'label' => 'ภาระหนี้เดิมอ้างอิงต่อเดือน (บาท)', 'type' => 'number', 'required' => false, 'column' => 3],
                ['name' => 'collateral_value_ref', 'label' => 'ราคาประเมินหลักทรัพย์อ้างอิง (บาท)', 'type' => 'number', 'required' => false, 'column' => 3],
                ['name' => 'income_midpoint_ref', 'label' => 'รายได้อ้างอิงกลางช่วง (บาท/เดือน)', 'type' => 'number', 'required' => false, 'column' => 3],
                ['name' => 'recommended_installment', 'label' => 'ค่างวดแนะนำตาม DSR (บาท/เดือน)', 'type' => 'number', 'required' => false, 'column' => 3],
                ['name' => 'recommended_loan_amount', 'label' => 'วงเงินแนะนำอัตโนมัติ (บาท)', 'type' => 'number', 'required' => false, 'column' => 3],
                ['name' => 'pd_target_pct', 'label' => 'PD เป้าหมายสูงสุด (%)', 'type' => 'number', 'required' => false, 'column' => 3],
                ['name' => 'policy_note', 'label' => 'หมายเหตุ/เงื่อนไขเพิ่มเติม', 'type' => 'textarea', 'required' => false, 'column' => 3],
            ],
        ],
        'early_warning' => [
            'id' => 11,
            'code' => 'EWS',
            'title' => 'ระบบ Early Warning (EWS)',
            'description' => 'จับสัญญาณเตือนล่วงหน้า, watchlist และ feedback loop',
            'file' => '09_early_warning.php',
            'primary_ref_field' => 'alert_code',
            'primary_name_field' => 'customer_ref',
            'amount_field' => 'exposure_amount',
            'risk_field' => 'severity',
            'event_date_field' => 'alert_date',
            'fields' => [
                ['name' => 'alert_code', 'label' => 'รหัสแจ้งเตือน', 'type' => 'text', 'required' => true],
                ['name' => 'customer_ref', 'label' => 'อ้างอิงลูกค้า', 'type' => 'text', 'required' => true],
                ['name' => 'trigger_type', 'label' => 'ประเภท Trigger', 'type' => 'text', 'required' => true],
                ['name' => 'severity', 'label' => 'ระดับความรุนแรง', 'type' => 'select', 'required' => true, 'options' => ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']],
                ['name' => 'anomaly_detail', 'label' => 'รายละเอียดความผิดปกติ', 'type' => 'textarea', 'required' => false],
                ['name' => 'geo_field_note', 'label' => 'บันทึกพื้นที่ / ภาคสนาม', 'type' => 'textarea', 'required' => false],
                ['name' => 'recommended_action', 'label' => 'ข้อเสนอแนะในการดำเนินการ', 'type' => 'textarea', 'required' => false],
                ['name' => 'watchlist_flag', 'label' => 'อยู่ใน Watchlist', 'type' => 'select', 'required' => true, 'options' => ['YES', 'NO']],
                ['name' => 'feedback_result', 'label' => 'ผล Feedback', 'type' => 'select', 'required' => false, 'options' => ['PENDING', 'TRUE_POSITIVE', 'FALSE_POSITIVE']],
                ['name' => 'exposure_amount', 'label' => 'ยอด Exposure', 'type' => 'number', 'required' => false],
                ['name' => 'alert_date', 'label' => 'วันที่แจ้งเตือน', 'type' => 'date', 'required' => false],
            ],
        ],
        'pricing_limit' => [
            'id' => 12,
            'code' => 'PRC',
            'title' => 'ระบบกำหนดราคาแบบ Risk-based (Pricing & Limit)',
            'description' => 'กำหนดดอกเบี้ย, ค่าธรรมเนียม และวงเงินตาม risk band',
            'file' => '10_pricing_limit.php',
            'primary_ref_field' => 'pricing_code',
            'primary_name_field' => 'product_name',
            'amount_field' => 'credit_limit',
            'risk_field' => 'risk_band',
            'event_date_field' => 'effective_date',
            'fields' => [
                ['name' => 'pricing_code', 'label' => 'รหัสราคา', 'type' => 'text', 'required' => true],
                ['name' => 'product_name', 'label' => 'ชื่อผลิตภัณฑ์', 'type' => 'text', 'required' => true],
                ['name' => 'risk_band', 'label' => 'ช่วงความเสี่ยง', 'type' => 'select', 'required' => true, 'options' => ['A', 'B', 'C', 'D', 'E']],
                ['name' => 'interest_rate_pct', 'label' => 'อัตราดอกเบี้ย (%)', 'type' => 'number', 'required' => true],
                ['name' => 'fee_amount', 'label' => 'ค่าธรรมเนียม', 'type' => 'number', 'required' => false],
                ['name' => 'credit_limit', 'label' => 'วงเงินเครดิต', 'type' => 'number', 'required' => true],
                ['name' => 'cost_of_fund_pct', 'label' => 'ต้นทุนเงินทุน (%)', 'type' => 'number', 'required' => false],
                ['name' => 'expected_loss_pct', 'label' => 'ความเสียหายคาดการณ์ (%)', 'type' => 'number', 'required' => false],
                ['name' => 'margin_target_pct', 'label' => 'เป้าหมายส่วนต่างกำไร (%)', 'type' => 'number', 'required' => false],
                ['name' => 'campaign_override_note', 'label' => 'หมายเหตุแคมเปญ Override', 'type' => 'textarea', 'required' => false],
                ['name' => 'effective_date', 'label' => 'วันที่มีผลบังคับใช้', 'type' => 'date', 'required' => false],
            ],
        ],
        'legal_enforcement' => [
            'id' => 13,
            'code' => 'LGL',
            'title' => 'ระบบกฎหมายและบังคับคดี (Legal & Enforcement)',
            'description' => 'จัดการ pipeline คดี, เอกสาร, ทนาย และการบังคับคดี',
            'file' => '11_legal_enforcement.php',
            'primary_ref_field' => 'legal_case_no',
            'primary_name_field' => 'contract_no',
            'amount_field' => 'claim_amount',
            'risk_field' => 'enforcement_stage',
            'event_date_field' => 'court_date',
            'fields' => [
                ['name' => 'legal_case_no', 'label' => 'เลขคดี', 'type' => 'text', 'required' => true],
                ['name' => 'contract_no', 'label' => 'เลขที่สัญญา', 'type' => 'text', 'required' => true],
                ['name' => 'document_template', 'label' => 'แม่แบบเอกสาร', 'type' => 'text', 'required' => false],
                ['name' => 'notice_type', 'label' => 'ประเภทหนังสือ', 'type' => 'text', 'required' => false],
                ['name' => 'lawyer_name', 'label' => 'ชื่อทนาย', 'type' => 'text', 'required' => false],
                ['name' => 'evidence_repository', 'label' => 'แหล่งจัดเก็บหลักฐาน', 'type' => 'textarea', 'required' => false],
                ['name' => 'court_date', 'label' => 'วันนัดศาล', 'type' => 'date', 'required' => false],
                ['name' => 'seizure_status', 'label' => 'สถานะยึดทรัพย์', 'type' => 'text', 'required' => false],
                ['name' => 'enforcement_stage', 'label' => 'ขั้นตอนบังคับคดี', 'type' => 'text', 'required' => false],
                ['name' => 'claim_amount', 'label' => 'ยอดเรียกร้อง', 'type' => 'number', 'required' => false],
            ],
        ],
        'accounting_gl' => [
            'id' => 14,
            'code' => 'ACC',
            'title' => 'ระบบบัญชีและการเงิน (Accounting & GL + Lease/Loan)',
            'description' => 'ลงบัญชี GL, accrual/provision, กระทบยอด และนำเข้ารายการธนาคาร',
            'file' => '12_accounting_gl.php',
            'primary_ref_field' => 'journal_no',
            'primary_name_field' => 'coa_code',
            'amount_field' => 'debit_amount',
            'risk_field' => 'reconciliation_status',
            'event_date_field' => 'posting_date',
            'fields' => [
                ['name' => 'journal_no', 'label' => 'เลขที่ Journal', 'type' => 'text', 'required' => true],
                ['name' => 'coa_code', 'label' => 'ผังบัญชี', 'type' => 'text', 'required' => true],
                ['name' => 'posting_date', 'label' => 'วันที่ลงบัญชี', 'type' => 'date', 'required' => true],
                ['name' => 'entry_type', 'label' => 'ประเภทรายการ', 'type' => 'select', 'required' => true, 'options' => ['GL_POSTING', 'ACCRUAL', 'EIR', 'PROVISION', 'RECON']],
                ['name' => 'debit_amount', 'label' => 'ยอดเดบิต', 'type' => 'number', 'required' => false],
                ['name' => 'credit_amount', 'label' => 'ยอดเครดิต', 'type' => 'number', 'required' => false],
                ['name' => 'provision_rule', 'label' => 'กฎการตั้งสำรอง', 'type' => 'text', 'required' => false],
                ['name' => 'bank_statement_ref', 'label' => 'อ้างอิง Bank Statement', 'type' => 'text', 'required' => false],
                ['name' => 'reconciliation_status', 'label' => 'สถานะกระทบยอด', 'type' => 'select', 'required' => false, 'options' => ['PENDING', 'MATCHED', 'UNMATCHED']],
                ['name' => 'narration', 'label' => 'คำอธิบายรายการ', 'type' => 'textarea', 'required' => false],
            ],
        ],
        'compliance_audit' => [
            'id' => 15,
            'code' => 'CMP',
            'title' => 'ระบบกำกับดูแลและบันทึกการตรวจสอบ (Compliance + Audit Trail)',
            'description' => 'บันทึก consent, maker-checker, access control และร่องรอยตรวจสอบ',
            'file' => '13_compliance_audit.php',
            'primary_ref_field' => 'audit_case_no',
            'primary_name_field' => 'action_type',
            'amount_field' => 'risk_score',
            'risk_field' => 'control_status',
            'event_date_field' => 'audit_date',
            'fields' => [
                ['name' => 'audit_case_no', 'label' => 'เลขที่เคสตรวจสอบ', 'type' => 'text', 'required' => true],
                ['name' => 'consent_type', 'label' => 'ประเภทความยินยอม', 'type' => 'text', 'required' => false],
                ['name' => 'pdpa_log_ref', 'label' => 'อ้างอิง PDPA Log', 'type' => 'text', 'required' => false],
                ['name' => 'action_type', 'label' => 'ประเภทการกระทำ', 'type' => 'text', 'required' => true],
                ['name' => 'maker_user', 'label' => 'ผู้บันทึก', 'type' => 'text', 'required' => false],
                ['name' => 'checker_user', 'label' => 'ผู้ตรวจสอบ', 'type' => 'text', 'required' => false],
                ['name' => 'approval_reason', 'label' => 'เหตุผลการอนุมัติ', 'type' => 'textarea', 'required' => false],
                ['name' => 'ip_device', 'label' => 'IP / อุปกรณ์', 'type' => 'text', 'required' => false],
                ['name' => 'immutable_hash', 'label' => 'ค่า Immutable Hash', 'type' => 'text', 'required' => false],
                ['name' => 'control_status', 'label' => 'สถานะการควบคุม', 'type' => 'select', 'required' => false, 'options' => ['OPEN', 'IN_PROGRESS', 'CLOSED']],
                ['name' => 'risk_score', 'label' => 'คะแนนความเสี่ยง', 'type' => 'number', 'required' => false],
                ['name' => 'audit_date', 'label' => 'วันที่ตรวจสอบ', 'type' => 'date', 'required' => false],
            ],
        ],
        'risk_lab' => [
            'id' => 16,
            'code' => 'RLB',
            'title' => 'ระบบ Simulation / Monte Carlo พอร์ต (Risk Lab)',
            'description' => 'จำลองสถานการณ์ด้วย PD/LGD distribution และคาดการณ์ loss/capital',
            'file' => '14_risk_lab.php',
            'primary_ref_field' => 'run_no',
            'primary_name_field' => 'scenario_name',
            'amount_field' => 'forecast_loss',
            'risk_field' => 'capital_need',
            'event_date_field' => 'run_date',
            'fields' => [
                ['name' => 'run_no', 'label' => 'เลขที่รัน', 'type' => 'text', 'required' => true],
                ['name' => 'scenario_name', 'label' => 'ชื่อสถานการณ์', 'type' => 'text', 'required' => true],
                ['name' => 'macro_proxy', 'label' => 'ตัวแปรมหภาคอ้างอิง', 'type' => 'text', 'required' => false],
                ['name' => 'pd_distribution', 'label' => 'การกระจายตัว PD', 'type' => 'textarea', 'required' => false],
                ['name' => 'lgd_distribution', 'label' => 'การกระจายตัว LGD', 'type' => 'textarea', 'required' => false],
                ['name' => 'correlation_assumption', 'label' => 'สมมติฐานสหสัมพันธ์', 'type' => 'textarea', 'required' => false],
                ['name' => 'prior_setting', 'label' => 'การตั้งค่า Prior', 'type' => 'textarea', 'required' => false],
                ['name' => 'forecast_loss', 'label' => 'ความเสียหายคาดการณ์', 'type' => 'number', 'required' => false],
                ['name' => 'capital_need', 'label' => 'เงินกองทุนที่ต้องใช้', 'type' => 'number', 'required' => false],
                ['name' => 'governance_note', 'label' => 'หมายเหตุ Model Governance', 'type' => 'textarea', 'required' => false],
                ['name' => 'run_date', 'label' => 'วันที่รัน', 'type' => 'date', 'required' => false],
            ],
        ],
        'scenario_stress' => [
            'id' => 17,
            'code' => 'STR',
            'title' => 'ระบบจำลองสถานการณ์และ Stress Test (What-if Dashboard)',
            'description' => 'วิเคราะห์ผลกระทบต่อ NPL, กำไร และสภาพคล่องจากสถานการณ์จำลอง',
            'file' => '15_scenario_stress.php',
            'primary_ref_field' => 'stress_case_no',
            'primary_name_field' => 'stress_type',
            'amount_field' => 'projected_profit',
            'risk_field' => 'projected_npl_pct',
            'event_date_field' => 'run_date',
            'fields' => [
                ['name' => 'stress_case_no', 'label' => 'เลขที่เคสจำลอง', 'type' => 'text', 'required' => true],
                ['name' => 'baseline_period', 'label' => 'ช่วงเวลาฐานเปรียบเทียบ', 'type' => 'text', 'required' => true],
                ['name' => 'stress_type', 'label' => 'ประเภทการทดสอบ', 'type' => 'text', 'required' => true],
                ['name' => 'rate_shift_pct', 'label' => 'การปรับดอกเบี้ย (%)', 'type' => 'number', 'required' => false],
                ['name' => 'income_drop_pct', 'label' => 'รายได้ลดลง (%)', 'type' => 'number', 'required' => false],
                ['name' => 'disaster_factor', 'label' => 'ปัจจัยภัยพิบัติ', 'type' => 'number', 'required' => false],
                ['name' => 'roll_rate_shift_pct', 'label' => 'การเปลี่ยนแปลง Roll-rate (%)', 'type' => 'number', 'required' => false],
                ['name' => 'collection_capacity_pct', 'label' => 'กำลังติดตามหนี้ (%)', 'type' => 'number', 'required' => false],
                ['name' => 'projected_npl_pct', 'label' => 'NPL คาดการณ์ (%)', 'type' => 'number', 'required' => false],
                ['name' => 'projected_profit', 'label' => 'กำไรคาดการณ์', 'type' => 'number', 'required' => false],
                ['name' => 'run_date', 'label' => 'วันที่รัน', 'type' => 'date', 'required' => false],
            ],
        ],
        'executive_bi_api' => [
            'id' => 18,
            'code' => 'EXE',
            'title' => 'ระบบผู้บริหาร + API เชื่อมภายนอก (Executive BI + Integration)',
            'description' => 'รวม KPI ผู้บริหาร, การเชื่อม API และการติดตาม webhook',
            'file' => '16_executive_bi_api.php',
            'primary_ref_field' => 'integration_no',
            'primary_name_field' => 'dashboard_type',
            'amount_field' => 'data_quality_score',
            'risk_field' => 'sync_status',
            'event_date_field' => 'sync_date',
            'fields' => [
                ['name' => 'integration_no', 'label' => 'เลขที่การเชื่อมต่อ', 'type' => 'text', 'required' => true],
                ['name' => 'dashboard_type', 'label' => 'ประเภทแดชบอร์ด', 'type' => 'text', 'required' => true],
                ['name' => 'kpi_snapshot', 'label' => 'ภาพรวม KPI', 'type' => 'textarea', 'required' => false],
                ['name' => 'data_quality_score', 'label' => 'คะแนนคุณภาพข้อมูล', 'type' => 'number', 'required' => false],
                ['name' => 'api_partner', 'label' => 'คู่ค้า API', 'type' => 'text', 'required' => false],
                ['name' => 'api_endpoint', 'label' => 'ปลายทาง API', 'type' => 'text', 'required' => false],
                ['name' => 'api_key_ref', 'label' => 'อ้างอิง API Key', 'type' => 'text', 'required' => false],
                ['name' => 'webhook_url', 'label' => 'URL สำหรับ Webhook', 'type' => 'text', 'required' => false],
                ['name' => 'sync_status', 'label' => 'สถานะการเชื่อมต่อ', 'type' => 'select', 'required' => true, 'options' => ['READY', 'SUCCESS', 'FAILED', 'PAUSED']],
                ['name' => 'integration_log_ref', 'label' => 'อ้างอิง Integration Log', 'type' => 'textarea', 'required' => false],
                ['name' => 'sync_date', 'label' => 'วันที่ซิงก์', 'type' => 'date', 'required' => false],
            ],
        ],
        'local_economy_lei' => [
            'id' => 19,
            'code' => 'LEI',
            'title' => 'Local Economy Market Index (LEI)',
            'description' => 'Capture local price and economic environment data by branch for PD/LGD/NPL assessments.',
            'file' => '17_local_economy_lei.php',
            'search_placeholder' => 'Search report code, branch, or survey date',
            'primary_ref_field' => 'lei_report_no',
            'primary_name_field' => 'branch_code',
            'amount_field' => 'fuel_price_per_liter',
            'risk_field' => 'period_type',
            'event_date_field' => 'period_date',
            'fields' => [
                ['name' => 'lei_report_no', 'label' => "\u{0E23}\u{0E2B}\u{0E31}\u{0E2A}\u{0E23}\u{0E32}\u{0E22}\u{0E07}\u{0E32}\u{0E19} LEI", 'type' => 'text', 'required' => true],
                ['name' => 'branch_code', 'label' => "\u{0E2A}\u{0E32}\u{0E02}\u{0E32}", 'type' => 'branch', 'required' => true],
                ['name' => 'period_type', 'label' => "\u{0E04}\u{0E27}\u{0E32}\u{0E21}\u{0E16}\u{0E35}\u{0E48}\u{0E02}\u{0E49}\u{0E2D}\u{0E21}\u{0E39}\u{0E25}", 'type' => 'select', 'required' => true, 'options' => ['WEEKLY', 'MONTHLY']],
                ['name' => 'period_date', 'label' => "\u{0E27}\u{0E31}\u{0E19}\u{0E17}\u{0E35}\u{0E48}\u{0E2A}\u{0E33}\u{0E23}\u{0E27}\u{0E08}/\u{0E2A}\u{0E34}\u{0E49}\u{0E19}\u{0E23}\u{0E2D}\u{0E1A}", 'type' => 'date', 'required' => true],

                ['name' => 'rice_5kg_price', 'label' => "\u{0E02}\u{0E49}\u{0E32}\u{0E27}\u{0E2A}\u{0E32}\u{0E23} 5 \u{0E01}\u{0E01}.", 'type' => 'number', 'required' => false],
                ['name' => 'egg_no3_tray_price', 'label' => "\u{0E44}\u{0E02}\u{0E48}\u{0E44}\u{0E01}\u{0E48}\u{0E40}\u{0E1A}\u{0E2D}\u{0E23}\u{0E4C} 3 (\u{0E15}\u{0E48}\u{0E2D}\u{0E41}\u{0E1C}\u{0E07})", 'type' => 'number', 'required' => false],
                ['name' => 'pork_red_meat_price_kg', 'label' => "\u{0E2B}\u{0E21}\u{0E39}\u{0E40}\u{0E19}\u{0E37}\u{0E49}\u{0E2D}\u{0E41}\u{0E14}\u{0E07} (\u{0E1A}\u{0E32}\u{0E17}/\u{0E01}\u{0E01}.)", 'type' => 'number', 'required' => false],
                ['name' => 'chicken_breast_price_kg', 'label' => "\u{0E2D}\u{0E01}\u{0E44}\u{0E01}\u{0E48} (\u{0E1A}\u{0E32}\u{0E17}/\u{0E01}\u{0E01}.)", 'type' => 'number', 'required' => false],
                ['name' => 'cooking_oil_1l_price', 'label' => "\u{0E19}\u{0E49}\u{0E33}\u{0E21}\u{0E31}\u{0E19}\u{0E1E}\u{0E37}\u{0E0A} 1 \u{0E25}\u{0E34}\u{0E15}\u{0E23}", 'type' => 'number', 'required' => false],
                ['name' => 'sugar_price_kg', 'label' => "\u{0E19}\u{0E49}\u{0E33}\u{0E15}\u{0E32}\u{0E25}\u{0E17}\u{0E23}\u{0E32}\u{0E22} (\u{0E1A}\u{0E32}\u{0E17}/\u{0E01}\u{0E01}.)", 'type' => 'number', 'required' => false],
                ['name' => 'instant_noodle_pack_price', 'label' => "\u{0E1A}\u{0E30}\u{0E2B}\u{0E21}\u{0E35}\u{0E48}\u{0E01}\u{0E36}\u{0E48}\u{0E07}\u{0E2A}\u{0E33}\u{0E40}\u{0E23}\u{0E47}\u{0E08}\u{0E23}\u{0E39}\u{0E1B} (\u{0E15}\u{0E48}\u{0E2D}\u{0E41}\u{0E1E}\u{0E47}\u{0E04})", 'type' => 'number', 'required' => false],
                ['name' => 'kitchen_veg_price', 'label' => "\u{0E1C}\u{0E31}\u{0E01}\u{0E2A}\u{0E27}\u{0E19}\u{0E04}\u{0E23}\u{0E31}\u{0E27}\u{0E2B}\u{0E25}\u{0E31}\u{0E01} (\u{0E15}\u{0E48}\u{0E2D}\u{0E02}\u{0E35}\u{0E14})", 'type' => 'number', 'required' => false],

                ['name' => 'street_food_plate_price', 'label' => "\u{0E01}\u{0E4B}\u{0E27}\u{0E22}\u{0E40}\u{0E15}\u{0E35}\u{0E4B}\u{0E22}\u{0E27}/\u{0E2D}\u{0E32}\u{0E2B}\u{0E32}\u{0E23}\u{0E15}\u{0E32}\u{0E21}\u{0E2A}\u{0E31}\u{0E48}\u{0E07}", 'type' => 'number', 'required' => false],
                ['name' => 'curry_rice_two_item_price', 'label' => "\u{0E02}\u{0E49}\u{0E32}\u{0E27}\u{0E23}\u{0E32}\u{0E14}\u{0E41}\u{0E01}\u{0E07} 2 \u{0E2D}\u{0E22}\u{0E48}\u{0E32}\u{0E07}", 'type' => 'number', 'required' => false],
                ['name' => 'thai_tea_price', 'label' => "\u{0E01}\u{0E32}\u{0E41}\u{0E1F}\u{0E42}\u{0E1A}\u{0E23}\u{0E32}\u{0E13}/\u{0E0A}\u{0E32}\u{0E40}\u{0E22}\u{0E47}\u{0E19}", 'type' => 'number', 'required' => false],
                ['name' => 'bottled_water_600ml_price', 'label' => "\u{0E19}\u{0E49}\u{0E33}\u{0E14}\u{0E37}\u{0E48}\u{0E21} 600 \u{0E21}\u{0E25}.", 'type' => 'number', 'required' => false],
                ['name' => 'standard_set_meal_price', 'label' => "\u{0E2D}\u{0E32}\u{0E2B}\u{0E32}\u{0E23}\u{0E0A}\u{0E38}\u{0E14} Standard", 'type' => 'number', 'required' => false],

                ['name' => 'fuel_price_per_liter', 'label' => "\u{0E19}\u{0E49}\u{0E33}\u{0E21}\u{0E31}\u{0E19}\u{0E40}\u{0E1A}\u{0E19}\u{0E0B}\u{0E34}\u{0E19}/\u{0E14}\u{0E35}\u{0E40}\u{0E0B}\u{0E25} (\u{0E15}\u{0E48}\u{0E2D}\u{0E25}\u{0E34}\u{0E15}\u{0E23})", 'type' => 'number', 'required' => false],
                ['name' => 'motorbike_taxi_fare', 'label' => "\u{0E04}\u{0E48}\u{0E32}\u{0E23}\u{0E16}\u{0E21}\u{0E2D}\u{0E40}\u{0E15}\u{0E2D}\u{0E23}\u{0E4C}\u{0E44}\u{0E0B}\u{0E04}\u{0E4C}\u{0E23}\u{0E31}\u{0E1A}\u{0E08}\u{0E49}\u{0E32}\u{0E07}", 'type' => 'number', 'required' => false],
                ['name' => 'public_transport_fare', 'label' => "\u{0E04}\u{0E48}\u{0E32}\u{0E42}\u{0E14}\u{0E22}\u{0E2A}\u{0E32}\u{0E23}\u{0E23}\u{0E16}\u{0E2A}\u{0E32}\u{0E18}\u{0E32}\u{0E23}\u{0E13}\u{0E30}", 'type' => 'number', 'required' => false],
                ['name' => 'parking_hourly_fee', 'label' => "\u{0E04}\u{0E48}\u{0E32}\u{0E08}\u{0E2D}\u{0E14}\u{0E23}\u{0E16} (\u{0E15}\u{0E48}\u{0E2D}\u{0E0A}\u{0E31}\u{0E48}\u{0E27}\u{0E42}\u{0E21}\u{0E07})", 'type' => 'number', 'required' => false],
                ['name' => 'lpg_15kg_price', 'label' => "\u{0E01}\u{0E4A}\u{0E32}\u{0E0B}\u{0E2B}\u{0E38}\u{0E07}\u{0E15}\u{0E49}\u{0E21} 15 \u{0E01}\u{0E01}.", 'type' => 'number', 'required' => false],

                ['name' => 'men_haircut_price', 'label' => "\u{0E04}\u{0E48}\u{0E32}\u{0E15}\u{0E31}\u{0E14}\u{0E1C}\u{0E21}\u{0E0A}\u{0E32}\u{0E22}", 'type' => 'number', 'required' => false],
                ['name' => 'laundry_service_price', 'label' => "\u{0E04}\u{0E48}\u{0E32}\u{0E0B}\u{0E31}\u{0E01}\u{0E23}\u{0E35}\u{0E14}", 'type' => 'number', 'required' => false],
                ['name' => 'internet_mobile_monthly_fee', 'label' => "\u{0E04}\u{0E48}\u{0E32}\u{0E2D}\u{0E34}\u{0E19}\u{0E40}\u{0E17}\u{0E2D}\u{0E23}\u{0E4C}\u{0E40}\u{0E19}\u{0E47}\u{0E15}/\u{0E21}\u{0E37}\u{0E2D}\u{0E16}\u{0E37}\u{0E2D} \u{0E15}\u{0E48}\u{0E2D}\u{0E40}\u{0E14}\u{0E37}\u{0E2D}\u{0E19}", 'type' => 'number', 'required' => false],
                ['name' => 'electricity_unit_rate', 'label' => "\u{0E04}\u{0E48}\u{0E32}\u{0E44}\u{0E1F}\u{0E15}\u{0E48}\u{0E2D}\u{0E2B}\u{0E19}\u{0E48}\u{0E27}\u{0E22}", 'type' => 'number', 'required' => false],
                ['name' => 'water_unit_rate', 'label' => "\u{0E04}\u{0E48}\u{0E32}\u{0E19}\u{0E49}\u{0E33}\u{0E1B}\u{0E23}\u{0E30}\u{0E1B}\u{0E32}\u{0E15}\u{0E48}\u{0E2D}\u{0E2B}\u{0E19}\u{0E48}\u{0E27}\u{0E22}", 'type' => 'number', 'required' => false],

                ['name' => 'local_population_count', 'label' => 'ประชากรในพื้นที่ (คน)', 'type' => 'number', 'required' => false],
                ['name' => 'floating_population_count', 'label' => 'ประชากรแฝง (คน)', 'type' => 'number', 'required' => false],
                ['name' => 'pass_through_population_count', 'label' => 'ประชากรผ่าน/คนสัญจร (คน)', 'type' => 'number', 'required' => false],
                ['name' => 'job_opening_count', 'label' => 'ตำแหน่งงาน/แรงงานที่ต้องการ (คน)', 'type' => 'number', 'required' => false],
                ['name' => 'factory_worker_count', 'label' => 'แรงงานจากโรงงาน (คน)', 'type' => 'number', 'required' => false],
                ['name' => 'retail_worker_count', 'label' => 'แรงงานจากร้านค้า (คน)', 'type' => 'number', 'required' => false],
                ['name' => 'hospital_worker_count', 'label' => 'แรงงานจากโรงพยาบาล (คน)', 'type' => 'number', 'required' => false],
                ['name' => 'company_worker_count', 'label' => 'แรงงานจากบริษัท (คน)', 'type' => 'number', 'required' => false],
                ['name' => 'partnership_worker_count', 'label' => 'แรงงานจากห้างหุ้นส่วน (คน)', 'type' => 'number', 'required' => false],
                ['name' => 'government_project_worker_count', 'label' => 'แรงงานจากโครงการภาครัฐ (คน)', 'type' => 'number', 'required' => false],
                ['name' => 'business_count', 'label' => 'จำนวนธุรกิจในพื้นที่ (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'restaurant_count', 'label' => 'จำนวนร้านอาหาร (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'government_office_count', 'label' => 'จำนวนสถานที่ราชการ (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'school_count', 'label' => 'จำนวนโรงเรียน/สถานศึกษา (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'government_project_count', 'label' => 'จำนวนโครงการรัฐที่ดำเนินอยู่ (โครงการ)', 'type' => 'number', 'required' => false],
                ['name' => 'gas_station_count', 'label' => 'จำนวนปั๊มน้ำมัน (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'tourist_attraction_count', 'label' => 'จำนวนแหล่งท่องเที่ยว (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'large_mall_count', 'label' => 'จำนวนห้างขนาดใหญ่ (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'market_count', 'label' => 'จำนวนตลาด (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'agricultural_area_rai', 'label' => 'พื้นที่การเกษตร (ไร่)', 'type' => 'number', 'required' => false],
                ['name' => 'hospital_count', 'label' => 'จำนวนโรงพยาบาล/คลินิก (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'industrial_estate_count', 'label' => 'จำนวนนิคม/โซนอุตสาหกรรม (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'warehouse_logistics_count', 'label' => 'จำนวนศูนย์กระจายสินค้า/คลัง (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'hotel_lodging_count', 'label' => 'จำนวนโรงแรม/ที่พัก (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'bank_branch_count', 'label' => 'จำนวนสาขาธนาคาร (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'atm_count', 'label' => 'จำนวนจุด ATM/CDM (จุด)', 'type' => 'number', 'required' => false],
                ['name' => 'convenience_store_count', 'label' => 'จำนวนร้านสะดวกซื้อ (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'transport_hub_count', 'label' => 'จำนวนจุดขนส่งหลัก (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'university_vocational_count', 'label' => 'จำนวนมหาวิทยาลัย/อาชีวะ (แห่ง)', 'type' => 'number', 'required' => false],
                ['name' => 'construction_project_count', 'label' => 'จำนวนโครงการก่อสร้างที่เดินงาน (โครงการ)', 'type' => 'number', 'required' => false],
                ['name' => 'rental_housing_unit_count', 'label' => 'จำนวนห้องเช่า/ที่พักอาศัยให้เช่า (ยูนิต)', 'type' => 'number', 'required' => false],
                ['name' => 'night_market_count', 'label' => 'จำนวนตลาดนัด/ถนนคนเดิน (แห่ง)', 'type' => 'number', 'required' => false],

                ['name' => 'soap_shampoo_price', 'label' => "\u{0E2A}\u{0E1A}\u{0E39}\u{0E48}/\u{0E22}\u{0E32}\u{0E2A}\u{0E23}\u{0E30}\u{0E1C}\u{0E21}", 'type' => 'number', 'required' => false],
                ['name' => 'detergent_medium_bag_price', 'label' => "\u{0E1C}\u{0E07}\u{0E0B}\u{0E31}\u{0E01}\u{0E1F}\u{0E2D}\u{0E01} (\u{0E16}\u{0E38}\u{0E07}\u{0E01}\u{0E25}\u{0E32}\u{0E07})", 'type' => 'number', 'required' => false],
                ['name' => 'tissue_pack_24_roll_price', 'label' => "\u{0E01}\u{0E23}\u{0E30}\u{0E14}\u{0E32}\u{0E29}\u{0E17}\u{0E34}\u{0E0A}\u{0E0A}\u{0E39}\u{0E48} (\u{0E41}\u{0E1E}\u{0E47}\u{0E04} 24 \u{0E21}\u{0E49}\u{0E27}\u{0E19})", 'type' => 'number', 'required' => false],

                ['name' => 'beer_can_price', 'label' => "\u{0E40}\u{0E1A}\u{0E35}\u{0E22}\u{0E23}\u{0E4C}\u{0E01}\u{0E23}\u{0E30}\u{0E1B}\u{0E4B}\u{0E2D}\u{0E07}", 'type' => 'number', 'required' => false],
                ['name' => 'cigarette_pack_price', 'label' => "\u{0E23}\u{0E32}\u{0E04}\u{0E32}\u{0E1A}\u{0E38}\u{0E2B}\u{0E23}\u{0E35}\u{0E48} 1 \u{0E0B}\u{0E2D}\u{0E07}", 'type' => 'number', 'required' => false],
                ['name' => 'movie_ticket_price', 'label' => "\u{0E04}\u{0E48}\u{0E32}\u{0E15}\u{0E31}\u{0E4B}\u{0E27}\u{0E2B}\u{0E19}\u{0E31}\u{0E07}", 'type' => 'number', 'required' => false],
                ['name' => 'rent_room_monthly_price', 'label' => "\u{0E04}\u{0E48}\u{0E32}\u{0E40}\u{0E0A}\u{0E48}\u{0E32}\u{0E2B}\u{0E2D}\u{0E1E}\u{0E31}\u{0E01}/\u{0E1A}\u{0E49}\u{0E32}\u{0E19}\u{0E40}\u{0E0A}\u{0E48}\u{0E32}", 'type' => 'number', 'required' => false],
                ['name' => 'actual_daily_wage', 'label' => "\u{0E04}\u{0E48}\u{0E32}\u{0E41}\u{0E23}\u{0E07}\u{0E02}\u{0E31}\u{0E49}\u{0E19}\u{0E15}\u{0E48}\u{0E33}\u{0E17}\u{0E35}\u{0E48}\u{0E08}\u{0E48}\u{0E32}\u{0E22}\u{0E08}\u{0E23}\u{0E34}\u{0E07}", 'type' => 'number', 'required' => false],

                ['name' => 'lei_note', 'label' => "\u{0E2B}\u{0E21}\u{0E32}\u{0E22}\u{0E40}\u{0E2B}\u{0E15}\u{0E38}\u{0E40}\u{0E0A}\u{0E34}\u{0E07}\u{0E1E}\u{0E37}\u{0E49}\u{0E19}\u{0E17}\u{0E35}\u{0E48}", 'type' => 'textarea', 'required' => false],
            ],
        ],        'loan_payment_history' => [
            'id' => 20,
            'code' => 'PAY',
            'title' => 'ระบบชำระเงินกู้และประวัติการชำระ (Loan Payment & History)',
            'description' => 'บันทึกรับชำระรายงวด อัปเดตสถานะค้างชำระ และตรวจสอบประวัติการชำระย้อนหลังต่อสัญญา',
            'file' => '18_loan_payment_history.php',
            'primary_ref_field' => 'payment_no',
            'primary_name_field' => 'contract_no',
            'amount_field' => 'paid_amount',
            'risk_field' => 'payment_status',
            'event_date_field' => 'payment_date',
            'fields' => [
                ['name' => 'payment_no', 'label' => 'เลขที่รายการชำระ', 'type' => 'text', 'required' => true],
                ['name' => 'contract_no', 'label' => 'เลขที่สัญญา', 'type' => 'text', 'required' => true],
                ['name' => 'customer_ref', 'label' => 'รหัสลูกค้า', 'type' => 'text', 'required' => false],
                ['name' => 'installment_no', 'label' => 'งวดที่ชำระ', 'type' => 'number', 'required' => false],
                ['name' => 'due_date', 'label' => 'วันครบกำหนดงวด', 'type' => 'date', 'required' => false],
                ['name' => 'payment_date', 'label' => 'วันที่รับชำระ', 'type' => 'date', 'required' => true],
                ['name' => 'amount_due', 'label' => 'ยอดที่ต้องชำระ', 'type' => 'number', 'required' => false],
                ['name' => 'principal_paid', 'label' => 'เงินต้นที่ชำระ', 'type' => 'number', 'required' => false],
                ['name' => 'interest_paid', 'label' => 'ดอกเบี้ยที่ชำระ', 'type' => 'number', 'required' => false],
                ['name' => 'fee_paid', 'label' => 'ค่าธรรมเนียมที่ชำระ', 'type' => 'number', 'required' => false],
                ['name' => 'penalty_paid', 'label' => 'เบี้ยปรับที่ชำระ', 'type' => 'number', 'required' => false],
                ['name' => 'paid_amount', 'label' => 'ยอดรับชำระรวม', 'type' => 'number', 'required' => true],
                ['name' => 'remaining_balance', 'label' => 'เงินต้นคงเหลือหลังรับชำระ', 'type' => 'number', 'required' => false],
                ['name' => 'dpd_after_payment', 'label' => 'DPD หลังรับชำระ', 'type' => 'number', 'required' => false],
                ['name' => 'payment_channel', 'label' => 'ช่องทางชำระ', 'type' => 'select', 'required' => true, 'options' => ['CASH', 'BANK_TRANSFER', 'QR', 'AUTO_DEBIT', 'COUNTER_SERVICE', 'OTHER']],
                ['name' => 'receipt_no', 'label' => 'เลขที่ใบเสร็จ', 'type' => 'text', 'required' => false],
                ['name' => 'collector_name', 'label' => 'ผู้รับชำระ/พนักงานรับเงิน', 'type' => 'text', 'required' => false],
                ['name' => 'payment_status', 'label' => 'สถานะการชำระ', 'type' => 'select', 'required' => true, 'options' => ['PAID', 'PARTIAL', 'OVERPAID', 'PENDING_CLEARING', 'REVERSED']],
                ['name' => 'history_note', 'label' => 'หมายเหตุประวัติการชำระ', 'type' => 'textarea', 'required' => false],
                [
                    'name' => 'payment_history_items',
                    'label' => 'รายการประวัติที่เกี่ยวข้อง (เพิ่มได้หลายรายการ)',
                    'type' => 'json_list',
                    'required' => false,
                    'button_label' => 'เพิ่มรายการประวัติการชำระ',
                    'list_columns' => [
                        ['key' => 'history_date', 'label' => 'วันที่', 'input' => 'date', 'required' => true],
                        ['key' => 'history_type', 'label' => 'ประเภทรายการ', 'input' => 'select', 'required' => true, 'options' => ['SCHEDULED', 'PAYMENT', 'PROMISE_TO_PAY', 'REVERSAL', 'WAIVER', 'RESTRUCTURE']],
                        ['key' => 'history_amount', 'label' => 'จำนวนเงิน', 'input' => 'number', 'required' => false],
                        ['key' => 'history_ref', 'label' => 'อ้างอิง', 'input' => 'text', 'required' => false],
                        ['key' => 'history_status', 'label' => 'สถานะ', 'input' => 'select', 'required' => false, 'options' => ['SUCCESS', 'PENDING', 'FAILED', 'CANCELLED']],
                        ['key' => 'history_note', 'label' => 'หมายเหตุ', 'input' => 'text', 'required' => false],
                    ],
                ],
            ],
        ],
    ];
}

function module_by_key(string $key): array
{
    $modules = all_modules();
    if (!isset($modules[$key])) {
        throw new RuntimeException('Module not found: ' . $key);
    }

    $module = ($modules[$key] + ['key' => $key]);
    return ui_localize_module_definition($module);
}

function module_routes(): array
{
    $routes = [];
    foreach (all_modules() as $key => $module) {
        $routes[$key] = 'modules/' . $module['file'];
    }
    return $routes;
}


